### ISSUE TITLE
Missing CI?

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vhost-user-backend#17]
@slp it looks like this crate does not run tests on each PR. The rust-vmm-ci does not seem to be properly initialized as a submodule. Is there another CI that's running?

**Comment by slp** [comment]
@andreeaflorescu No, there's no other CI. Could be because we're missing the `.buildkite` directory, or is there some other reason why this isn't working?

**Comment by andreeaflorescu** [comment]
There were some miss configurations in Buildkite. The .buildkite repository is not required, just the rust-vmm-ci one is needed, and that one I see is already there.

I did a dry-run here: #19 and it seems to be working now. Can you also do a push force on your PR to re-trigger the build?

**Comment by slp** [comment]
> I did a dry-run here: #19 and it seems to be working now. Can you also do a push force on your PR to re-trigger the build?

Yeah, seems to be working now. Thanks!
