### ISSUE TITLE
Add some unit tests ?

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/vhost-user-backend#24]
Can someone familiar with this code add some unit-tests for this repository? I am required to add some tests for the backend device part in https://github.com/rust-vmm/vhost-device/ and not very sure of how to add those ..

**Comment by jiangliu** [comment]
This pending PR (#23 ) adds some unit test cases, but the coverage is still around 70%, we still need to add more unit test cases.

**Comment by vireshk** [comment]
> This pending PR (#23 ) adds some unit test cases, but the coverage is still around 70%, we still need to add more unit test cases.

Ahh, I missed that. I will look into details to see if I can copy some of the stuff to get better testing for my stuff :)

Thanks @jiangliu
