### ISSUE TITLE
Any plans to switch to vmm-sys-utils/epoll?

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vhost-user-backend#42]
I noticed that this crate already has vmm-sys-util as a dependency, so I was wondering if we could also use the [`epoll`](https://docs.rs/vmm-sys-util/0.9.0/vmm_sys_util/epoll/index.html) module from vmm-sys-util instead of importing another external crate.

**Comment by jiangliu** [comment]
sure, that will make it easier to maintain dependency.

**Comment by jiangliu** [comment]
> I agree, I can take a look at it next week if no one is working on it already ;-)

aha, I missed this message:(
