### ISSUE TITLE
Upgrade the virtio-queue dependency to the latest vm-virtio revision

### ISSUE THREAD

**Issue by mathieupoirier** [rust-vmm/vhost-user-backend#47]
Using the latest virtio-queue revision is the first step in allowing crates that include vhost-user-backend to test different Mutex/RwLockVring manipulations.  The [MockSplitQueue](https://github.com/rust-vmm/vm-virtio/blob/22b288ad4703794ca14d68345754122051363b2f/crates/virtio-queue/src/mock.rs#L227) implements the virtio backend side of the equation and is able to insert DescriptorChains in the VringMutex/RwLocks.  Those are then processed by the handle_event() method of types that implement the VhostUserBackend and VhostUserBackendMut traits.

**Comment by mathieupoirier** [comment]
I'm not sure to understand the above comment but from looking at PR8198885, is seems like the same thing needs to be done here with vhost-user-backend.

**Comment by stefano-garzarella** [comment]
That commit is for this crate, and now is merged in the `main` branch, so you should have the latest API of `virtio-queue` available here.

If you agree, we can close this issue.

**Comment by mathieupoirier** [comment]
Apologies for the late follow-up - I did not see the last line of the latest comment.  Thanks for doing that - I will start looking into integrating with the MockSplitQueue in the comings days.
