### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/vhost-user-backend#62]
Could someone tag a new release for the `vhost-user-backend` crate so that Cloud Hypervisor can rely on it rather than using the latest commit from the main branch?
Apart from that, given that there are plans to update/simplify `virtio-queue`, this might/will bring breaking changes, therefore it might be a good idea to tag a release before `virtio-queue` is getting updated.

**Comment by andreeaflorescu** [comment]
It think we might also need to bumb the virtio-queue version in vhost-user-backend for the next release.

**Comment by sboeuf** [comment]
Yes let me send a quick PR for that.

**Comment by sboeuf** [comment]
https://github.com/rust-vmm/vhost-user-backend/pull/63
